from __future__ import annotations
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any

from google.oauth2 import service_account
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError


SCOPES = [
    "https://www.googleapis.com/auth/documents",
    "https://www.googleapis.com/auth/drive.file",
]


def get_google_services_from_user_token(access_token: str):
    """
    Build Docs + Drive clients using the USER's OAuth token.
    The doc is created in THEIR Drive, not ours.
    """
    try:
        credentials = Credentials(token=access_token)
        docs_service = build(
            "docs", "v1",
            credentials=credentials,
            cache_discovery=False
        )
        drive_service = build(
            "drive", "v3",
            credentials=credentials,
            cache_discovery=False
        )
        return docs_service, drive_service
    except Exception as e:
        print(f"Failed to build Google services from user token: {e}")
        return None, None


def create_governance_report(
    audit_data: dict[str, Any],
    metrics: dict[str, Any],
    gemini_summary: str | None = None,
    google_access_token: str | None = None,   # <-- NEW parameter
    share_with_email: str | None = None,
) -> dict[str, str]:

    # Use user token — never service account
    if not google_access_token:
        return {
            "success": False,
            "error": "google_token_required",
            "message": "Google authorisation required to export."
        }

    docs_service, drive_service = get_google_services_from_user_token(
        google_access_token
    )

    if not docs_service:
        return {
            "success": False,
            "error": "google_auth_failed",
            "message": "Could not connect to Google. Token may have expired."
        }

    dataset = audit_data.get("dataset_name", "Unknown Dataset")
    domain = audit_data.get("domain", "hiring")
    score = metrics.get("fairness_score", 0)
    di = metrics.get("disparate_impact", 0)
    date = datetime.now().strftime("%B %d, %Y")
    title = f"FairFlow AI — {domain.title()} Fairness Audit Report — {date}"

    try:
        doc = docs_service.documents().create(
            body={"title": title}
        ).execute()
        doc_id = doc["documentId"]

        risk_level = (
            "HIGH RISK" if di < 0.6
            else "MEDIUM RISK" if di < 0.8
            else "LOW RISK"
        )

        content = f"""FairFlow AI — Fairness Audit Report
Generated: {date}
Dataset: {dataset}
Domain: {domain.title()}

EXECUTIVE SUMMARY

Overall Fairness Score: {score:.0f} / 100
Risk Level: {risk_level}
Disparate Impact: {di:.4f} (threshold: > 0.80)

{'⚠ BIAS DETECTED — Action required before deployment.' if di < 0.8 else '✓ Fairness threshold met — continue monitoring.'}

FAIRNESS METRICS

Disparate Impact: {di:.4f} {'FAIL' if di < 0.8 else 'PASS'}
Statistical Parity Difference: {metrics.get('stat_parity_diff', 0):.4f} {'FAIL' if abs(metrics.get('stat_parity_diff', 0)) > 0.1 else 'PASS'}
Equal Opportunity Difference: {metrics.get('equal_opp_diff', 0):.4f} {'FAIL' if abs(metrics.get('equal_opp_diff', 0)) > 0.1 else 'PASS'}
Average Odds Difference: {metrics.get('avg_odds_diff', 0):.4f} {'FAIL' if abs(metrics.get('avg_odds_diff', 0)) > 0.1 else 'PASS'}

AI COMPLIANCE ANALYSIS

{gemini_summary or 'Run Gemini analysis to generate compliance summary.'}

RECOMMENDED ACTIONS

1. Review all flagged candidates in FairFlow AI candidate explorer.
2. Apply the recommended mitigation strategy before production deployment.
3. Schedule re-audit after any changes to the decision pipeline.
4. Share this report with your legal and compliance team.

AUDIT CERTIFICATE

This report was generated by FairFlow AI.
SDG 10.3 — Reduced Inequalities
Audit timestamp: {datetime.now().isoformat()}

---
FairFlow AI • Reducing AI Discrimination in Hiring, Lending & Healthcare
"""

        docs_service.documents().batchUpdate(
            documentId=doc_id,
            body={"requests": [{"insertText": {"location": {"index": 1}, "text": content}}]}
        ).execute()

        # No need to set "anyone can view" — it's in the user's own Drive
        # They can share it however they choose

        return {
            "success": True,
            "doc_id": doc_id,
            "doc_url": f"https://docs.google.com/document/d/{doc_id}/edit",
            "title": title,
        }

    except HttpError as exc:
        print(f"HttpError details: {exc.content}")
        return {"success": False, "error": str(exc)}
    except Exception as e:
        return {"success": False, "error": str(e)}
