from __future__ import annotations
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any

from google.oauth2 import service_account
from googleapiclient.discovery import build


SCOPES = [
    "https://www.googleapis.com/auth/documents",
    "https://www.googleapis.com/auth/drive.file",
]


def get_google_services():
    sa_path = os.getenv(
        "GOOGLE_SERVICE_ACCOUNT_JSON",
        "google_service_account.json"
    )
    
    if not Path(sa_path).exists():
        # Try alternate paths
        alt_paths = [
            Path("google_service_account.json"),
            Path("/app/google_service_account.json"),
            Path(__file__).parent / "google_service_account.json",
        ]
        for p in alt_paths:
            if p.exists():
                sa_path = str(p)
                break
        else:
            print(f"Service account not found at {sa_path}")
            return None, None
    
    try:
        credentials = (
            service_account.Credentials
            .from_service_account_file(
                sa_path,
                scopes=SCOPES
            )
        )
        docs_service = build(
            "docs", "v1", 
            credentials=credentials,
            cache_discovery=False
        )
        drive_service = build(
            "drive", "v3", 
            credentials=credentials,
            cache_discovery=False
        )
        print(f"Google services initialized from {sa_path}")
        return docs_service, drive_service
    except Exception as e:
        print(f"Google auth error: {e}")
        return None, None


def create_governance_report(
    audit_data: dict[str, Any],
    metrics: dict[str, Any],
    gemini_summary: str | None = None,
    share_with_email: str | None = None,
) -> dict[str, str]:
    print(f"Attempting Google Docs creation...")
    print(f"SA path env: {os.getenv('GOOGLE_SERVICE_ACCOUNT_JSON')}")
    print(f"DOCS_ENABLED: {os.getenv('GOOGLE_DOCS_ENABLED')}")
    
    docs_service, drive_service = (
        get_google_services()
    )
    
    if not docs_service:
        return {
            "success": False,
            "error": "Google Docs not configured",
        }
    
    dataset = audit_data.get(
        "dataset_name", "Unknown Dataset"
    )
    domain = audit_data.get("domain", "hiring")
    score = metrics.get("fairness_score", 0)
    di = metrics.get("disparate_impact", 0)
    date = datetime.now().strftime(
        "%B %d, %Y"
    )
    
    title = (
        f"FairFlow AI — {domain.title()} "
        f"Fairness Audit Report — {date}"
    )
    
    # Create the document
    try:
        doc = docs_service.documents().create(
            body={"title": title}
        ).execute()
        doc_id = doc["documentId"]
        
        # Build document content
        risk_level = (
            "HIGH RISK" if di < 0.6 
            else "MEDIUM RISK" if di < 0.8 
            else "LOW RISK"
        )
        
        content = f"""FairFlow AI — Fairness Audit Report
Generated: {date}
Dataset: {dataset}
Domain: {domain.title()}

EXECUTIVE SUMMARY

Overall Fairness Score: {score:.0f} / 100
Risk Level: {risk_level}
Disparate Impact: {di:.4f} (threshold: > 0.80)

{'⚠ BIAS DETECTED — Action required before deployment.' if di < 0.8 else '✓ Fairness threshold met — continue monitoring.'}

FAIRNESS METRICS

Disparate Impact: {di:.4f} {'FAIL' if di < 0.8 else 'PASS'}
Statistical Parity Difference: {metrics.get('stat_parity_diff', 0):.4f} {'FAIL' if abs(metrics.get('stat_parity_diff', 0)) > 0.1 else 'PASS'}
Equal Opportunity Difference: {metrics.get('equal_opp_diff', 0):.4f} {'FAIL' if abs(metrics.get('equal_opp_diff', 0)) > 0.1 else 'PASS'}
Average Odds Difference: {metrics.get('avg_odds_diff', 0):.4f} {'FAIL' if abs(metrics.get('avg_odds_diff', 0)) > 0.1 else 'PASS'}

AI COMPLIANCE ANALYSIS

{gemini_summary or 'Run Gemini analysis to generate compliance summary.'}

RECOMMENDED ACTIONS

1. Review all candidates flagged with bias status in FairFlow AI candidate explorer.
2. Apply the recommended mitigation strategy before production deployment.  
3. Schedule re-audit after any changes to the decision pipeline.
4. Share this report with your legal and compliance team for review.

AUDIT CERTIFICATE

This report was generated by FairFlow AI.
SDG 10.3 — Reduced Inequalities
Audit timestamp: {datetime.now().isoformat()}

---
FairFlow AI • Reducing AI Discrimination in Hiring, Lending & Healthcare
"""
        
        # Insert content into document
        requests = [
            {
                "insertText": {
                    "location": {"index": 1},
                    "text": content,
                }
            }
        ]
        
        docs_service.documents().batchUpdate(
            documentId=doc_id,
            body={"requests": requests}
        ).execute()
        
        # Make document publicly viewable
        # (avoids domain restriction issues)
        try:
            drive_service.permissions().create(
                fileId=doc_id,
                body={
                    "type": "anyone",
                    "role": "reader",
                },
            ).execute()
            
            # Also try to share with specific email
            if share_with_email:
                try:
                    drive_service.permissions().create(
                        fileId=doc_id,
                        body={
                            "type": "user",
                            "role": "writer",
                            "emailAddress": share_with_email,
                        },
                        sendNotificationEmail=False,
                    ).execute()
                except Exception:
                    pass  # Public link still works
                    
        except Exception as e:
            print(f"Sharing error: {e}")
            # Document still created, just not shared
        
        doc_url = (
            f"https://docs.google.com/document/d/"
            f"{doc_id}/edit"
        )
        
        return {
            "success": True,
            "doc_id": doc_id,
            "doc_url": doc_url,
            "title": title,
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
        }
